version: '2'
services:
  nginx:
    image: bitnami/nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx-persistence:/bitnami/nginx
      - ./app:/app
    links:
      - phpfpm
    domainname: docker.dev
  phpfpm:
    image: bitnami/php-fpm
    volumes:
      - ./app:/app