version: '2'
services:
  nginx:
    image: bitnami/nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx-persistence:/bitnami/nginx
      - ./app:/app
    links:
      - phpfpm
    domainname: docker.dev
  phpfpm:
    image: bitnami/php-fpm
    volumes:
      - ./app:/app
    links:
      - dbmaster
      - dbslave
  dbmaster:
    image: bitnami/mariadb:latest
    environment:
      #- ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_PASSWORD=dockertest
      - MARIADB_USER=dockertest
      - MARIADB_PASSWORD=dockertest
      - MARIADB_DATABASE=dockertest
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
    ports:
      - "3306:3306"
    volumes:
      - ./dbmaster-persistence:/bitnami/mariadb
  dbslave:
    image: bitnami/mariadb:latest
    environment:
      #- ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_PASSWORD=dockertest
      - MARIADB_MASTER_HOST=master
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_MASTER_ROOT_PASSWORD=dockertest
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
    ports:
      - "3307:3306"
    volumes:
      - ./dbslave-persistence:/bitnami/mariadb
    depends_on:
      - dbmaster